name: Terraform Pipeline

on:
  push:
    branches:
      - terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@v2
        with:
          env:
            access_key: ${{ secrets.ACCESS_KEY }}
            secret_key: ${{ secrets.SECRET_KEY }}
     
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -recursive -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
