name: Terraform Pipeline

on:
  push:
    branches:
      - terraform

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@v2
